name: browser
version: 0.9.1
authors: ["Dart Team <misc@dartlang.org>"]
homepage: http://www.dartlang.org
description: >
 The bootstrap dart.js script for Dart apps running in the browser.
environment:
  sdk: ">=0.8.10+6 <2.0.0"
