name: angular-perf
version: 0.10.0
description: Angular benchmarks
dependencies:
  angular:
    path: ..
dev_dependencies:
  benchmark_harness: '>=1.0.0'
  unittest: '>=0.10.1 <0.12.0'
  mock: '>=0.10.0 <0.12.0'
