name: bwu_datagrid
version: 0.0.11
author: Günter Zöchbauer <guenter@gzoechbauer.com>
description: BWU Datagrid is A Polymer.dart grid/spreadsheet element inspired by SlickGrid.
homepage: https://github.com/bwu-dart/bwu_datagrid
documentation: http://bwu-dart.github.io/bwu_datagrid/dartdoc/
environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  polymer: '>=0.11.0-dev <0.12.0'
  quiver: '>=0.18.2 <0.19.0'
  quiver_log: '>=1.0.1 <2.0.0'

  bwu_utils_browser: '>=0.0.2 <0.1.0'
#    path: ../../bwu_utils_browser
  bwu_sparkline: '>=0.0.2 <0.1.0'
     #path: ../bwu_sparkline

dev_dependencies:
  unittest: any

dependency_overrides:
#  barback: '>= 0.14.0+3'
#  analyzer: '>= 0.15.5'

transformers:
- polymer:
    entry_points:
    - example/e01_simple.html
    - example/e02_formatters.html
    - example/e07_events.html
    - example/e14_highlighting.html
    - example/e03_editing.html
    - example/e03a_compound_editors.html
    - example/e03b_editing_with_undo.html
    - example/composite_editor_item_details.html
    - example/totals_via_data_provider.html
    - example/e04_model.html
    - example/e05_collapsing.html
    - example/e08_alternative_display.html
    - example/e09_row_reordering.html
    - example/e10_async_post_render.html
    - example/autotooltips.html
