name: di
version: 0.0.40
authors:
- Vojta Jina <vojta.jina@gmail.com>
- Pavel Jbanov <pavelgj@gmail.com>
description: Dependency Injection framework
homepage: https://github.com/angular/di.dart
environment:
  sdk: '>=0.8.10'
dependencies:
  analyzer: '>=0.13.0 <0.14.0'
  barback: '>=0.11.1 <0.14.0'
  code_transformers: '>=0.1.3 <0.2.0'
  path: ">=0.9.0 <2.0.0"
dev_dependencies:
  benchmark_harness: any
  unittest: any
  browser: any

transformers:
- di:
    injectable_annotations: di.tests.InjectableTest
