name: html5lib
version: 0.11.0+1
author: Dart Team <misc@dartlang.org>
description: A library for working with HTML documents.
homepage: http://pub.dartlang.org/packages/html5lib
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  csslib: '>=0.10.0 <0.11.0'
  source_maps: '>=0.9.1 <0.10.0'
  utf: '>=0.9.0 <0.10.0'
dev_dependencies:
  path: '>=0.9.0 <2.0.0'
  unittest: '>=0.10.0 <0.11.0'
