name: bwu_utils_browser
version: 0.0.2
description: utils that depend on 'dart:html'
homepage: https://github.com/bwu-dart/bwu_utils_browser
author: Günter Zöchbauer <guenter@gzoechbauer.com>
environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  bwu_utils: '>=0.0.1 <0.1.0'
#    path: ../bwu_utils

dev_dependencies:
  unittest: any